### ISSUE TITLE
IndexError: index 579 is out of bounds for axis 0 with size 579

### ISSUE THREAD

**Issue by liupeiID** [ramanpreet1990/CSE_573_Wavelet_Edge_Detection#1]
haarConvolveRowsLowPass :
(1159, 1770)
Traceback (most recent call last):
  File "Wavelet_Edge_Detection_Project.py", line 561, in <module>
    threshold_original_haar)
  File "Wavelet_Edge_Detection_Project.py", line 340, in pipeline
    img_LL_2 = performLL(img_input, filter_wavelet)
  File "Wavelet_Edge_Detection_Project.py", line 259, in performLL
    img_L_rows_downsampled = downSample(img_L_rows, direction_rows)
  File "Wavelet_Edge_Detection_Project.py", line 78, in downSample
    img_output[new, :] = img_input[i, :]
IndexError: index 579 is out of bounds for axis 0 with size 579

shell returned 1

Press ENTER or type command to continue

**Comment by aishangcengloua** [comment]
The size of the input image is required to be a multiple of 4
